Upgrade SimpleWebauthn to version 9
Something about how transitive dependencies interact was causing this error on login (assertion):

```
Error: Cannot get schema for 'ECDSASigValue' target
    at AsnSchemaStorage.get (/node_modules/@simplewebauthn/server/node_modules/@peculiar/asn1-schema/build/cjs/schema.js:17:19)
    at Function.fromASN (/node_modules/@simplewebauthn/server/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:26:52)
    at Function.parse (/node_modules/@simplewebauthn/server/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:16:26)
    at unwrapEC2Signature (/node_modules/@simplewebauthn/server/src/helpers/iso/isoCrypto/unwrapEC2Signature.ts:12:37)
    at Object.verify (/node_modules/@simplewebauthn/server/src/helpers/iso/isoCrypto/verify.ts:26:50)
    at verifySignature (/node_modules/@simplewebauthn/server/src/helpers/verifySignature.ts:34:20)
    at Object.verifyAuthenticationResponse (/node_modules/@simplewebauthn/server/src/authentication/verifyAuthenticationResponse.ts:206:36)
```

Upgrading SimpleWebauthn to version 9.x together with a `yarn upgrade` seems to
have fixed this. This may be related to an issue fixed in version 8.3.6 of
SimpleWebauthn:
https://github.com/MasterKale/SimpleWebAuthn/blob/master/CHANGELOG.md#v836